///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class ToDoData {
/*
{
  "title": "ASDASDASAS",
  "description": "aASDasdasd",
  "createdAt": "2024-10-15T19:00:35.5957652",
  "user": null,
  "userId": 1,
  "isComplated": false,
  "id": 7,
  "isDeleted": false
}
*/

  String? title;
  String? description;
  String? createdAt;
  String? user;
  int? userId;
  bool? isComplated;
  int? id;
  bool? isDeleted;

  ToDoData({
    this.title,
    this.description,
    this.createdAt,
    this.user,
    this.userId,
    this.isComplated,
    this.id,
    this.isDeleted,
  });
  ToDoData.fromJson(Map<String, dynamic> json) {
    title = json['title']?.toString();
    description = json['description']?.toString();
    createdAt = json['createdAt']?.toString();
    user = json['user']?.toString();
    userId = json['userId']?.toInt();
    isComplated = json['isComplated'];
    id = json['id']?.toInt();
    isDeleted = json['isDeleted'];
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['title'] = title;
    data['description'] = description;
    data['createdAt'] = createdAt;
    data['user'] = user;
    data['userId'] = userId;
    data['isComplated'] = isComplated;
    data['id'] = id;
    data['isDeleted'] = isDeleted;
    return data;
  }
    @override
  String toString() {
    return 'ToDoData(title: $title, description: $description, createdAt: $createdAt, user: $user, userId: $userId, isComplated: $isComplated, id: $id, isDeleted: $isDeleted)';
  }
}

class ToDo {
/*
{
  "data": [
    {
      "title": "ASDASDASAS",
      "description": "aASDasdasd",
      "createdAt": "2024-10-15T19:00:35.5957652",
      "user": null,
      "userId": 1,
      "isComplated": false,
      "id": 7,
      "isDeleted": false
    }
  ],
  "success": true,
  "message": null
}
*/

  List<ToDoData>? data;
  bool? success;
  String? message;

  ToDo({
    this.data,
    this.success,
    this.message,
  });
  ToDo.fromJson(Map<String, dynamic> json) {
    if (json['data'] != null) {
      final v = json['data'];
      final arr0 = <ToDoData>[];
      v.forEach((v) {
        arr0.add(ToDoData.fromJson(v));
      });
      this.data = arr0;
    }
    success = json['success'];
    message = json['message']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (this.data != null) {
      final v = this.data;
      final arr0 = [];
      v?.forEach((v) {
        arr0.add(v.toJson());
      });
      data['data'] = arr0;
    }
    data['success'] = success;
    data['message'] = message;
    return data;
  }
    @override
  String toString() {
    return 'ToDo(data: $data, success: $success, message: $message)';
  }
}
